version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./backend/database:/app/database
      - ./models:/app/models
    environment:
      - SECRET_KEY=infrapredict-secret-key-super-secure-sih2026-essor-prime

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
